### ISSUE TITLE
One should install websocket-client

### ISSUE THREAD

**Issue by SolanaExpert2022** [yulz008/orb_cryptoBot#1]
Hello
I think you made a mistake.
What is needed is "pip install websocket-client"

**Comment by yulz008** [comment]
Hi SolanaExpert2022, yeah you're right. I have missed that one. It should be "pip install websocket-client".  I'll update the instruction. Thanks for your inputs!! :)

**Comment by SolanaExpert2022** [comment]
You're welcome !
